# Training configuration

illumination:
  azimuth: 225
  altitude: 45
  darkest_shadow_surface:
    - 0.2
    - 0.0
    - 0.0
    - 1.0
  brightest_lit_surface:
    - 0.7
    - 0.7
    - 1.0
    - 1.0

backgrounds:
  download: False
  images_per_term: 2
  search_terms:
    - office