# Training configuration

backgrounds:
  download: False
  images_per_term: 2
  search_terms:
    - office

img_size:
  w: 400
  h: 300

normalization:
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225

num_classes: 8
batch_size: 8
use_gpu: True